services:
  bot:
    image: local/quartzbot:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quartzbot
    hostname: quartzbot
    restart: unless-stopped
    tty: true
    volumes:
      - ./src:/app/src
      - db-data:/app/data
    env_file:
      - .env
    depends_on:
      cache:
        condition: service_healthy
    stop_signal: SIGINT
    stop_grace_period: 10s
    init: true

  cache:
    image: registry.redict.io/redict:7-alpine
    container_name: redict
    hostname: quartzbot-redict
    restart: unless-stopped
    expose:
      - "6379"
    healthcheck:
      test: [ "CMD", "redict-cli", "ping" ]
      start_interval: 1s
      start_period: 10s
      interval: 30s
      timeout: 3s
      retries: 5
    command: >
      redict-server 
      --maxmemory 200mb 
      --maxmemory-policy allkeys-lru

volumes:
  db-data:
